const templates = {
  attribute: {
    profile: {
      1: {
        type: 1,
        minimum: 0,
        maximum: 1,
        unit: '',
        step_value: 1,
        editable: 1,
      },
      2: {
        type: 2,
        minimum: 0,
        maximum: 100,
        unit: '%',
        step_value: 1,
        editable: 1,
      },
      3: {
        type: 3,
        minimum: 0,
        maximum: 5000,
        step_value: 1,
        editable: 0,
        unit: 'W',
      },
      4: {
        type: 4,
        minimum: 0,
        maximum: 10000,
        step_value: 0.01,
        editable: 0,
        unit: 'kWh',
      },
      5: {
        type: 5,
        minimum: -50,
        maximum: 125,
        unit: '°C',
        step_value: 0.5,
        editable: 0,
      },
      6: {
        type: 6,
        minimum: 0,
        maximum: 28,
        unit: '°C',
        step_value: 0.5,
        editable: 1,
      },
      7: {
        type: 7,
        minimum: 0,
        maximum: 100,
        step_value: 1,
        editable: 0,
        unit: '%',
      },
      8: {
        type: 8,
        minimum: 0,
        maximum: 100,
        unit: '%',
        step_value: 1,
        editable: 0,
      },
      10: {
        type: 10,
        minimum: 0,
        maximum: 2,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      11: {
        type: 11,
        minimum: 0,
        maximum: 100000,
        unit: 'lx',
        step_value: 1,
        editable: 0,
      },
      13: {
        type: 13,
        minimum: 0,
        maximum: 1,
        unit: '',
        step_value: 1,
        editable: 1,
      },
      15: {
        type: 15,
        minimum: 0,
        maximum: 100,
        unit: '%',
        step_value: 1,
        editable: 1,
      },
      20: {
        type: 20,
        minimum: 0,
        maximum: 5000,
        unit: 'ppm',
        step_value: 1,
        editable: 0,
      },
      23: {
        type: 23,
        minimum: 0,
        maximum: 16777215,
        unit: '',
        step_value: 1,
        editable: 1,
      },
      25: {
        type: 25,
        minimum: 0,
        maximum: 1,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      29: {
        type: 29,
        minimum: 1,
        maximum: 30,
        unit: 'min',
        step_value: 1,
        editable: 1,
      },
      33: {
        type: 33,
        minimum: 1,
        maximum: 4,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      40: {
        type: 40,
        minimum: 1,
        maximum: 2,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      42: {
        type: 42,
        minimum: 1700,
        maximum: 6500,
        unit: 'K',
        step_value: 1,
        editable: 1,
      },
      44: {
        type: 44,
        minimum: 0,
        maximum: 0,
        unit: 'text',
        step_value: 1,
        editable: 0,
      },
      45: {
        type: 45,
        minimum: 0,
        maximum: 0,
        unit: 'text',
        step_value: 1,
        editable: 0,
      },
      51: {
        type: 51,
        minimum: 0,
        maximum: 420,
        unit: 'V',
        step_value: 1,
        editable: 0,
      },
      69: {
        type: 69,
        minimum: 0,
        maximum: 1,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      70: {
        type: 70,
        minimum: 0,
        maximum: 1,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      84: {
        type: 84,
        minimum: 0,
        maximum: 0,
        unit: 'text',
        step_value: 1,
        editable: 0,
      },
      93: {
        type: 93,
        minimum: 0,
        maximum: 120,
        unit: 'dB',
        step_value: 1,
        editable: 0,
      },
      94: {
        type: 94,
        minimum: 0,
        maximum: 1160,
        unit: 'mBar',
        step_value: 5,
        editable: 0,
      },
      101: {
        type: 101,
        minimum: 0,
        maximum: 1,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      135: {
        type: 135,
        minimum: 0,
        maximum: 4,
        unit: 'n/a',
        step_value: 1,
        editable: 1,
      },
      144: {
        type: 144,
        minimum: 0,
        maximum: 3,
        unit: '',
        step_value: 1,
        editable: 1,
      },
      146: {
        type: 146,
        minimum: 0,
        maximum: 180,
        unit: 'km/h',
        step_value: 2,
        editable: 0,
      },
      147: {
        type: 147,
        minimum: 0,
        maximum: 15,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      168: {
        type: 168,
        minimum: 0,
        maximum: 50,
        unit: 'mm',
        step_value: 0.5,
        editable: 0,
      },
      169: {
        type: 169,
        minimum: 0,
        maximum: 1200,
        unit: 'mm',
        step_value: 5,
        editable: 0,
      },
      179: {
        type: 179,
        minimum: 0,
        maximum: 1,
        unit: 'n/a',
        step_value: 1,
        editable: 1,
      },
      181: {
        type: 181,
        minimum: 0,
        maximum: 1,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      182: {
        type: 182,
        minimum: 0,
        maximum: 1,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      193: {
        type: 193,
        minimum: 0,
        maximum: 70,
        unit: 'A',
        step_value: 1,
        editable: 0,
      },
      195: {
        type: 195,
        minimum: 0,
        maximum: 420,
        unit: 'V',
        step_value: 1,
        editable: 0,
      },
      205: {
        type: 205,
        minimum: 0,
        maximum: 5,
        unit: 'n/a',
        step_value: 1,
        editable: 1,
      },
      230: {
        type: 230,
        minimum: 0,
        maximum: 180,
        unit: 'km/h',
        step_value: 2,
        editable: 0,
      },
      231: {
        type: 231,
        minimum: 0,
        maximum: 15,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      232: {
        type: 232,
        minimum: 0,
        maximum: 4,
        unit: '',
        step_value: 1,
        editable: 1,
      },
      239: {
        type: 239,
        minimum: 0,
        maximum: 80000,
        unit: 'W',
        step_value: 1,
        editable: 0,
      },
      240: {
        type: 240,
        minimum: 0,
        maximum: 600000,
        unit: 'kWh',
        step_value: 1,
        editable: 0,
      },
      250: {
        type: 250,
        minimum: 0,
        maximum: 2,
        unit: 'n/a',
        step_value: 1,
        editable: 1,
      },
      251: {
        type: 251,
        minimum: 0,
        maximum: 2,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      252: {
        type: 252,
        minimum: 0,
        maximum: 1,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      253: {
        type: 253,
        minimum: 0,
        maximum: 1,
        unit: 'n/a',
        step_value: 1,
        editable: 0,
      },
      264: {
        type: 264,
        minimum: 0,
        maximum: 50000,
        unit: 'W',
        step_value: 100,
        editable: 0,
      },
      265: {
        type: 265,
        minimum: 0,
        maximum: 50000,
        unit: 'W',
        step_value: 100,
        editable: 0,
      },
      266: {
        type: 266,
        minimum: -50000,
        maximum: 50000,
        unit: 'W',
        step_value: 100,
        editable: 0,
      },
      267: {
        type: 267,
        minimum: -50000,
        maximum: 50000,
        unit: 'W',
        step_value: 100,
        editable: 0,
      },
      268: {
        type: 268,
        minimum: 0,
        maximum: 50000,
        unit: 'W',
        step_value: 100,
        editable: 0,
      },
      269: {
        type: 269,
        minimum: 0,
        maximum: 50000,
        unit: 'W',
        step_value: 100,
        editable: 0,
      },
      273: {
        type: 273,
        minimum: 0,
        maximum: 100,
        unit: '%',
        step_value: 1,
        editable: 0,
      },
      274: {
        type: 274,
        minimum: 0,
        maximum: 9999999,
        unit: 'kWh',
        step_value: 1,
        editable: 0,
      },
      275: {
        type: 275,
        minimum: 0,
        maximum: 9999999,
        unit: 'kWh',
        step_value: 1,
        editable: 0,
      },
      276: {
        type: 276,
        minimum: 0,
        maximum: 9999999,
        unit: 'kWh',
        step_value: 1,
        editable: 0,
      },
      277: {
        type: 277,
        minimum: 0,
        maximum: 9999999,
        unit: 'kWh',
        step_value: 1,
        editable: 0,
      },
      278: {
        type: 278,
        minimum: 0,
        maximum: 9999999,
        unit: 'kWh',
        step_value: 1,
        editable: 0,
      },
      279: {
        type: 279,
        minimum: 0,
        maximum: 9999999,
        unit: 'kWh',
        step_value: 1,
        editable: 0,
      },
      311: {
        type: 311,
        minimum: 0,
        maximum: 100,
        unit: '%Ram',
        step_value: 0.1,
        editable: 0,
      },
      312: {
        type: 312,
        minimum: 0,
        maximum: 100,
        unit: '%CPU',
        step_value: 0.1,
        editable: 0,
      },
      313: {
        type: 313,
        minimum: 0,
        maximum: 100,
        unit: '%Mem',
        step_value: 0.1,
        editable: 0,
      },
    },
  },
};

module.exports.find = function find(path) {
  const props = path.split('.');
  return props.reduce((p, c) => p && p[c], templates);
};
